data_dir: '../2_processed_data/whitened_data'
outdir: 'latent8' 
#
n_epochs: 10 
n_latent: 8
hidden_layer_sizes: [] 
#
do_em: True
em_bounds: [[0.1,0.4],[0.6,0.9],[0.6,0.9],[0.6,0.9]]  
em_batch_size: 150
nntype: 'nnutils.sae'
#
act_map: [0,1,1,1] 
lr: 0.0001
batch_size: 32
batch_output_freq: 300
epoch_output_freq: 2
test_batch_size: 1000
frac_test: 0.1
subsample: 1  
data_in_mem: True
#close_inds_fn: close_inds.npy #Only necessary if using a split autoencoder. np.array of the atom indices that go into classification task. See train_sample.txt.
#label_spreading: 'gaussian' #Optional parameter to draw initial labels from a normal distribution
